=== hmerinoc25-cloud/Erronka.2/Markatzekolengoaiak/hegaldiak/hegaldiak.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 
  <xs:element name="hegaldiak">
    <xs:complexType>
      <xs:sequence>
      
        <xs:element name="hegaldia" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="jatorria" type="xs:string"/>
              <xs:element name="helmuga" type="xs:string"/>
              <xs:element name="irteera" type="xs:time"/>
              <xs:element name="iritsiera" type="xs:time"/>
              <xs:element name="bidaiariak" type="xs:integer"/>
            </xs:sequence>

          
            <xs:attribute name="operadorea" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== hmerinoc25-cloud/Erronka.2/Markatzekolengoaiak/hegaldiak/hegaldiak.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Beharrezkoak direnak hegaldi bakoitzako:
- Atributuak: 
    - Operadorea: karaktere-kate datu mota
- Elementuak:
    - Jatorria eta helmuga: karaktere-kate datu mota
    - Irteera eta iritsiera: ordu datu mota
    - Bidaiariak: zenbakia
-->
<hegaldiak
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="hegaldiak.xsd">  

    <hegaldia operadorea="Vueling">
        <jatorria>Bilbo</jatorria>
        <helmuga>Madril</helmuga>
        <irteera>09:00:00</irteera> 
        <iritsiera>10:00:00</iritsiera>
        <bidaiariak>55</bidaiariak>
    </hegaldia>
    <hegaldia operadorea="Iberia">
        <jatorria>Bilbo</jatorria>
        <helmuga>Madril</helmuga>
        <irteera>12:45:00</irteera> 
        <iritsiera>13:45:00</iritsiera>
        <bidaiariak>75</bidaiariak>
    </hegaldia>
    <hegaldia operadorea="Iberia">
        <jatorria>Bilbo</jatorria>
        <helmuga>Bartzelona</helmuga>
        <irteera>08:30:00</irteera> 
        <iritsiera>09:30:00</iritsiera>
        <bidaiariak>50</bidaiariak>
    </hegaldia>
</hegaldiak>
